env:
  browser: true
globals:
  angular: false
  ionic: false
  _: false
  moment: false
  cordova: false
rules:
  consistent-this: 0
  func-names: 0
  max-params: 0
  max-statements: 0
  padded-blocks: 0
  no-param-reassign:
    - 1
    -
      props: false
